project_id = "alzxeplijnbpuqkfnpjk"

[functions.websocket-price-stream]
verify_jwt = false

[functions.tatum-price-logger]
verify_jwt = false

[functions.fetch-coinglass-coins]
verify_jwt = false

[functions.fetch-exchange-pairs]
verify_jwt = false

[functions.fetch-funding-history]
verify_jwt = false
