project_id = "alzxeplijnbpuqkfnpjk"

[functions.websocket-price-stream]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.populate-market-data]
verify_jwt = false

[functions.populate-coinglass-data]
verify_jwt = false

[functions.fetch-kraken-candles]
verify_jwt = false
