global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'relay'
    static_configs:
      - targets: ['host.docker.internal:4000']
        # when running locally without Docker use: ['localhost:4000']
    metrics_path: /metrics
